### ISSUE TITLE
Unable to load the task definition

### ISSUE THREAD

**Issue by jdshkolnik** [jbramwell/VSTS-Tools#2]
Hi,

I just installed the extension today for my on-premises TFS 2015 2.1 instance. I added the task as a build step to an existing definition but left it disabled. When I attempted to run it, I got:

##[error]Unable to load the task definition at I:\Agent\BuildAgent1\tasks\VSTSToolsListVariables\1.3.0\task.json

When I inspected the contents of that folder, I only saw a single file named "7ca7807a-6e3c-4ccd-9174-87a4eaf644dc.zip" with 0KB size.

**Comment by jbramwell** [comment]
@jdshkolnik I will be taking a look at this either today or tomorrow and I will follow back up here. Thanks for reporting this!

**Comment by jbramwell** [comment]
@jdshkolnik I installed a clean copy of **TFS 2015 Update 2.1** (v14.95.25229.0) and I have not been able to reproduce this issue. I installed the **List Variables** task as well as the **List Files** task. I tried running a build with just one task disable as well as a build with both tasks disabled and, finally, a build with both tasks added and enabled/disabled and the build completes successfully in all cases.

I tried the above on a Git-based repo as well as a TFVC-based repo.

At this point, I am wondering if there isn't something else going on with your build definition since the build doesn't seem to actually start running. The one time I recall seeing something like this in the past is when I was running a brand new (test) build against a team project that didn't have a Git-based repo setup yet.

Would you be able to try the tasks out on another build that is running successfully?

**Comment by jdshkolnik** [comment]
@jbramwell That is an amazing response, thank you. I'd be inclined toward your work from that alone.

I uninstalled from the collection, deleted the folder from within the agent tasks folder, and it now works. I can't explain how it happened. It's as if the extension installation for that agent was cut off prematurely.

**Comment by jbramwell** [comment]
@jdshkolnik Thanks for following up! I will report your experience to Microsoft (in case it can help them out in any way). For the time being, I'll consider this issue closed :-)

Thanks again!
